name: crypto_currency
description: An application for displaying crypto currencies rates.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  kiwi: ^0.2.0
  json_annotation: ^2.3.0
  http: ^0.12.0+2
  equatable: ^0.3.0
  flutter_svg: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.0
  kiwi_generator: ^0.4.0
  json_serializable: ^2.3.0
  mockito: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/